resources:
  #- namespace.yaml
  - storageclass.yaml
  - pv.yaml
  - pvc.yaml
  - configmap.yaml
  #- secret.yaml
  #- role.yaml
  #- clusterrole.yam
  #- rolebinding.yaml
  #- serviceaccount.yaml
  - deployment.yaml
  #- service.yaml
  #- ingress.yaml
