apiVersion: v1
kind: Service
metadata:
  name: gitlab-ce
  namespace: default
  labels:
    app: gitlab-ce
spec:
  type: NodePort
  selector:
    app: gitlab-ce
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 28080
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: 28081
    - name: ssh
      port: 2222
      targetPort: 2222
      nodePort: 28022
