apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: default
  labels:
    app: samba
spec:
  type: NodePort
  selector:
    app: samba
  ports:
    - name: http
      port: 445
      targetPort: 445
      nodePort: 445
