concurrent = 4
log_level = "debug"
check_interval = 5
[[runners]]
  name = "k8s-runner"
  url = "http://192.168.0.104:28080"
  token = ""
  executor = "kubernetes"
  builds_dir = "/home/gitlab"
  [runners.kubernetes]
    namespace = "default"
    #namespace_overwrite_allowed = "ci-.*"
    #bearer_token_overwrite_allowed = true

    allowed_pull_policies = ["always", "if-not-present", "never"]
    image = "almalinux:latest"
    pull_policy = "if-not-present"
    helper_image_pull_policy = "if-not-present"
    privileged = true

    #cpu_limit = "1"
    #memory_limit = "1Gi"
    #service_cpu_limit = "1"
    #service_memory_limit = "1Gi"
    #helper_cpu_limit = "500m"
    #helper_memory_limit = "100Mi"
    #poll_interval = 5
    #poll_timeout = 3600
    #dns_policy = "cluster-first"
    #logs_base_dir = "/tmp"
    #scripts_base_dir = "/tmp"
    #[runners.kubernetes.node_selector]
    #  gitlab = "true"
    [runners.kubernetes.node_tolerations]
      "node-role.kubernetes.io/control-plane" = "NoSchedule"

  [runners.docker]
    allowed_pull_policies = ["always", "if-not-present", "never"]
    image = "almalinux:latest"
    pull_policy = "if-not-present"
    helper_image_pull_policy = "if-not-present"
    privileged = true

    volumes = [
      "/home/gitlab:/home/gitlab",
      "/var/run/docker.sock:/var/run/docker.sock"

    ]
